import { PermissionKeys } from 'src/interface/dbinterface';

export const APP_CONSTANTS = {
  HOSTNAME: 'localhost',
  PORT: 3000,
  PATH: {
    USER: '/api/user',
    LOGIN: '/api/login',
    SIGNUP: '/api/signup',
    FORGOT_PASSWORD: '/api/forgot-password',
    RESET_PASSWORD: '/api/reset-password',
    FOLDERS: '/api/folders',
    FILES: '/api/files',
    FILEUPLOAD: '/api/files/upload',
    CREATEROLE: '/api/roles/create',
    UPDATEROLE: '/api/roles/update',
    DELETEROLE: '/api/roles/delete',
    GETROLES: '/api/roles/get',
    GETPERMISSIONS: '/api/permissions',
  },
  DATABASES: {
    USERSDB: 'user.db.json',
    FILESDB: 'file.db.json',
    FOLDERSDB: 'folder.db.json',
    ROLESDB: 'role.db.json',
  },
  CONSOLE_COLORS: {
    Reset: '\x1b[0m',
    Bright: '\x1b[1m',
    Dim: '\x1b[2m',
    Underscore: '\x1b[4m',
    Blink: '\x1b[5m',
    Reverse: '\x1b[7m',
    Hidden: '\x1b[8m',

    FgBlack: '\x1b[30m',
    FgRed: '\x1b[31m',
    FgGreen: '\x1b[32m',
    FgYellow: '\x1b[33m',
    FgBlue: '\x1b[34m',
    FgMagenta: '\x1b[35m',
    FgCyan: '\x1b[36m',
    FgWhite: '\x1b[37m',
    FgGray: '\x1b[90m',

    BgBlack: '\x1b[40m',
    BgRed: '\x1b[41m',
    BgGreen: '\x1b[42m',
    BgYellow: '\x1b[43m',
    BgBlue: '\x1b[44m',
    BgMagenta: '\x1b[45m',
    BgCyan: '\x1b[46m',
    BgWhite: '\x1b[47m',
    BgGray: '\x1b[100m',
  },
};

export const permissionKeys: PermissionKeys[] = [
  'canCreateFile',
  'canCreateFolder',
  'canDeleteFile',
  'canDeleteFolder',
  'canDownloadFile',
  'canDownloadFolder',
  'canRenameFile',
  'canRenameFolder',
  'canUploadFile',
  'canUploadFolder',
  'canViewFile',
  'canViewFolder',
];

// const Role: Role[] = [
//   {
//     _id: '608111111111111111111111',
//     name: 'Administrator',
//     permissions: {
//       canCreateFolder: true,
//       canCreateFile: true,
//       canDeleteFolder: true,
//       canDeleteFile: true,
//       canRenameFolder: true,
//       canRenameFile: true,
//       canUploadFile: true,
//       canDownloadFile: true,
//       canDownloadFolder: true,
//       canViewFile: true,
//       canViewFolder: true,
//     },
//     createdAt: '2021-04-01T00:00:00.000Z',
//     updatedAt: '2021-04-01T00:00:00.000Z',
//   },
//   {
//     _id: '608111111111111111111112',
//     name: 'Viewer',
//     permissions: {
//       canCreateFolder: false,
//       canCreateFile: false,
//       canDeleteFolder: false,
//       canDeleteFile: false,
//       canRenameFolder: false,
//       canRenameFile: false,
//       canUploadFile: false,
//       canDownloadFile: false,
//       canDownloadFolder: false,
//       canViewFile: true,
//       canViewFolder: true,
//     },
//     createdAt: '2021-04-01T00:00:00.000Z',
//     updatedAt: '2021-04-01T00:00:00.000Z',
//   },
//   {
//     _id: '608111111111111111111113',
//     name: 'Editor',
//     permissions: {
//       canCreateFolder: true,
//       canCreateFile: true,
//       canDeleteFolder: false,
//       canDeleteFile: false,
//       canRenameFolder: true,
//       canRenameFile: true,
//       canUploadFile: true,
//       canDownloadFile: true,
//       canDownloadFolder: true,
//       canViewFile: true,
//       canViewFolder: true,
//     },
//     createdAt: '2021-04-01T00:00:00.000Z',
//     updatedAt: '2021-04-01T00:00:00.000Z',
//   },
// ];
